export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
} as const;

export const RESPONSE_MESSAGES = {
  AUTH_REGISTER_SUCCESS: 'Admin registered successfully',
  AUTH_LOGIN_SUCCESS: 'Admin logged in successfully',
  AUTH_LOGOUT_SUCCESS: 'Admin logged out successfully',
  AUTH_PROFILE_FETCHED: 'Admin profile fetched successfully',
  INVALID_CREDENTIALS: 'Invalid email/username or password',
  EMAIL_ALREADY_EXISTS: 'Email already registered',
  USERNAME_ALREADY_EXISTS: 'Username already taken',
  ADMIN_NOT_FOUND: 'Admin not found',
  UNAUTHORIZED_ACCESS: 'Unauthorized access',
  INVALID_TOKEN: 'Invalid or expired token',
  TOKEN_MISSING: 'Authorization token is required',
  VALIDATION_ERROR: 'Validation error',
  INTERNAL_ERROR: 'Internal server error',
  OPERATION_SUCCESS: 'Operation completed successfully',
  RESULT_CREATED: 'Exam result created successfully',
  RESULT_DELETED: 'Exam result deleted successfully',
  RESULT_FETCHED: 'Exam results fetched successfully',
  RESULT_NOT_FOUND: 'Exam result not found',
  DUPLICATE_RESULT: 'Exam result for this year and type already exists',
  GALLERY_FETCHED: 'Gallery items fetched successfully',
  GALLERY_CREATED: 'Gallery item created successfully',
  VIDEO_FETCHED: 'Videos fetched successfully',
  VIDEO_CREATED: 'Video created successfully',
  DEMOGRAPHICS_FETCHED: 'Student demographics fetched successfully',
  DEMOGRAPHICS_CREATED: 'Student demographic created successfully',
  DEMOGRAPHICS_UPDATED: 'Student demographic updated successfully',
  DEMOGRAPHICS_DELETED: 'Student demographic deleted successfully',
  DEMOGRAPHICS_NOT_FOUND: 'Student demographic entry not found',
  DUPLICATE_DEMOGRAPHIC: 'A demographic entry for this grade already exists',
  CONTACT_CARDS_FETCHED: 'Contact cards fetched successfully',
  CONTACT_CARD_CREATED: 'Contact card created successfully',
  CONTACT_CARD_UPDATED: 'Contact card updated successfully',
  CONTACT_CARD_DELETED: 'Contact card deleted successfully',
  CONTACT_CARD_NOT_FOUND: 'Contact card not found',
  MESSAGE_SENT: 'Your message has been sent successfully',
  MESSAGES_FETCHED: 'Messages fetched successfully',
  MESSAGE_MARKED_READ: 'Message marked as read',
  MESSAGE_DELETED: 'Message deleted successfully',
  MESSAGE_NOT_FOUND: 'Message not found',
  SETTINGS_FETCHED: 'School settings fetched successfully',
  SETTINGS_UPDATED: 'School settings updated successfully',
} as const;

export const ADMIN_ROLES = {
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  STAFF: 'staff',
} as const;

export const ERROR_TYPES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTH_ERROR: 'AUTH_ERROR',
  NOT_FOUND_ERROR: 'NOT_FOUND_ERROR',
  CONFLICT_ERROR: 'CONFLICT_ERROR',
  SERVER_ERROR: 'SERVER_ERROR',
} as const;